# Generated by Django 2.2.28 on 2025-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhours',
            name='bookings_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bookings_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='standardhours',
            name='bookings_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
