# Generated by Django 2.2.28 on 2025-03-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_capacity',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
