# Generated by Django 2.2.28 on 2025-03-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250326_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardhours',
            name='week_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='customhours',
            unique_together={('restaurant', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='standardhours',
            unique_together={('restaurant', 'week_day')},
        ),
    ]
