# Generated by Django 2.2.28 on 2025-03-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250314_1810'),
        ('app', '0003_auto_20250314_1922'),
    ]

    operations = [
    ]
