# Generated by Django 2.2.28 on 2025-03-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250327_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
